validators:

- name: codecov-access-token
  rule_ids:
    - kingfisher.codecov.1

  http:
    method: GET
    url: "https://api.codecov.io/api/v2/github/"
    auth:
      type: bearer
      secret_group: "token"
    headers:
      - name: "Accept"
        value: "application/json"

    success_codes: [200]
    failure_codes: [401, 403]
